### ISSUE TITLE
Mejoras del proyecto

### ISSUE THREAD

**Issue by frandevaux** [frandevaux/ia-bullying#1]
Calcular correlacion entre columnas. A ojo o matriz de correlacion. Cramers V. Para descartar variables que hacen ruido.

Crear nuevas categoria en algunos casos para los nulls. Sexo: prefiero no decirlo

Verificar cuantas son las filas con por lo menos un null

**Comment by bautifrigole** [comment]
Se calculó la correlación entre cada feature utilizando Cramer's V. Los resultados se encuentran al final del archivo [EDA](https://github.com/frandevaux/ia-bullying/blob/develop/eda.md).

Se reemplazaron todos los nulls por 'Prefers not to answer' excepto en Custom_Age que se eliminaron las filas que tenían null en esa feature.

Se eliminaron las filas que contenían null en 'Bullied_on_school_property_in_past_12_months', 'Bullied_not_on_school_property_in_past_12_months' y 'Cyber_bullied_in_past_12_months' simultáneamente.
